# Introduction to TensorFlow
#### (Author : Soufiane Fadel)
\\

TensorFlow is the mathematical library created by the team of Google Brain at Google. Thanks to its dataflow programming, it's being heaving used as a deep learning library both in research and development sectors. Since its inception in 2015, TensorFlow has grown a very big community.

## Basic computations in TensorFlow

The base of TensorFlow is the computational graph, which we discussed earlier in this chapter, and tensors. A tensor is an n-dimensional vector. Thus, a scalar and a matrix variable is also a tensor. Here, we will try some of the basic computations to start with TensorFlow.

###### import Tensorflow 

In [0]:
import tensorflow as tf

Example of functions that instantiate basic tensors : 

* **tf.zeros() :** takes a tensor shape (that is, a tuple) and returns a tensor of that shape with all the values being zero.
* **tf.ones() :** akes a tensor shape but returns a tensor of that shape containing only ones.

In [0]:
tf.zeros(3)

<tf.Tensor 'zeros:0' shape=(3,) dtype=float32>

In [0]:
tf.ones(3)

<tf.Tensor 'ones:0' shape=(3,) dtype=float32>

As you can see, TensorFlow returns a reference to the tensor and not the value of the tensor. In order to get the value, we can use   **eval()**   or **run()**, a functions of tensor objects by running a session as follows:

In [0]:
a = tf.zeros(3)
with tf.Session() as sess: 
  sess.run(a)
  print(a.eval())

[0. 0. 0.]


Other methods to create a tensor of a certain shape and value are : **tf.fill()** and **tf.constant()**

In [0]:
a = tf.fill((2,2),value = 4) 
b = tf.constant(4,shape=(2,2))
with tf.Session() as sess: 
  print("a = ")
  print(sess.run(a))

  print("b = ")
  print(sess.run(b))


a = 
[[4 4]
 [4 4]]
b = 
[[4 4]
 [4 4]]


Next, we have functions that can **randomly initialize a tensor**. Among them, the most frequently used ones are:

* **tf.random_normal():**  Samples random values from the Normal distribution of specified mean and standard deviation

* **tf.random_uniform():** Samples random values from the Uniform distribution of a specified range

In [0]:
a = tf.random_normal((2,2), mean=0, stddev=1)
b = tf.random_uniform((2,2), minval=-3, maxval=3)
with tf.Session() as sess: 
  print("a = ")
  print(sess.run(a))
  print("b = ")
  print(sess.run(b))


a = 
[[-0.24760793 -0.09084689]
 [-0.6648181   0.07606685]]
b = 
[[ 1.3938894  1.9041147]
 [-2.0906582 -1.3587184]]


Variables in TensorFlow are holders for tensors and are defined by the function **tf.Variable():**

In [0]:
a = tf.Variable(tf.ones((2,2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

The evaluation fails in case of variables because they have to be explicitly initialized by using  **tf.global_varaibles_initializer()** 

In [0]:
a = tf.Variable(tf.ones((2,2))) 
with tf.Session() as sess: 
  sess.run(tf.global_variables_initializer()) 
  print(a.eval())

[[1. 1.]
 [1. 1.]]


Next in the queue, we have matrices. Identity matrices are square matrices with ones in the diagonal and zeros elsewhere. This can be done with the function ** tf.eye(): **
 


In [0]:
id = tf.eye(4)
with tf.Session() as sess:
  print(sess.run(id))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Similarly, there are diagonal matrices, which have values in the diagonal and zeros elsewhere, as shown here:

In [0]:
a = tf.range(1,5,1)
md = tf.diag(a)
mdn = tf.diag([1,2,5,3,2])
with tf.Session() as sess: 
  print("md = ")
  print(sess.run(md))
  print("mdn = ")
  print(sess.run(mdn))

md = 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
mdn = 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 5 0 0]
 [0 0 0 3 0]
 [0 0 0 0 2]]


We use the **tf.matrix_transpose()** function to transpose the given matrix, as shown here:

In [0]:
a = tf.ones((2,3))
b = tf.matrix_transpose(a)
with tf.Session() as sess: 
  print("a = ")
  print(sess.run(a))
  print("b = ")
  print(sess.run(b))

a = 
[[1. 1. 1.]
 [1. 1. 1.]]
b = 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


The next matrix operation is the **matrix multiplication** function as shown here. This is done by the function **tf.matmul()**

In [0]:
a = tf.ones((3,2))
b = tf.ones((2,4))
c = tf.matmul(a,b)
with tf.Session() as sess:
  print("a = ")
  print(sess.run(a))
  print("b = ")
  print(sess.run(b))
  print("c = ")
  print(sess.run(c))
  

a = 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
b = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c = 
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


Reshaping of tensors from one to another is done by using the **tf.reshape()**             function, as shown here: 

In [0]:
a = tf.ones((2,4))
b = tf.reshape(a,(8,))
c = tf.reshape(a,(2,2,2))
d = tf.reshape(b,(2,2,2))
with tf.Session() as sess:
  print("a = ")
  print(sess.run(a))
  print("b = ")
  print(sess.run(b))
  print("c = ")
  print(sess.run(c))
  print("d = ")
  print(sess.run(d))
  

a = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
b = 
[1. 1. 1. 1. 1. 1. 1. 1.]
c = 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
d = 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


The flow of computation in TensorFlow is represented as a computational graph, which is as instance of **tf.Graph()**. The graph contains tensors and operation objects, and keeps track of a series of operations and tensors involved. The default instance of the graph can be fetched by **tf.get_default_graph()** 

In [0]:
tf.get_default_graph()

We will explore complex operations, the creation of neural networks, and much more in TensorFlow in the coming notebooks.